# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7522aca4ea02022a99508b2403ae5aaaf1c080c1009cf9f3ce97e9d95724961e328e1c7c3f30ca6998b6cc6d9b6c0d10c5f40906c08cf901b92dd984087c7cd1

test:
  secret_key_base: 31f4cad6bb41ee3751f407c41f15fca94cf462f79ca4b133222213553e8996c31ae5f6c0f5f1d240d6689de01fe0b608da9d68fa6f761d5f7f75ba96e94296d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
